--- #YAML:1.0
name:                Locale-Maketext-Gettext
version:             1.21
abstract:            Joins gettext and Maketext frameworks
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - imacat <imacat@mail.imacat.idv.tw>
